apiVersion: v2
appVersion: 1.0.1
description: Prometheus Pingmesh Exporter
home: https://github.com/kubeservice-stack/pingmesh-agent
keywords:
- prometheus
- pimgmesh
- monitoring
maintainers:
- email: dongjiang1989@126.com
  name: dongjiang
name: prometheus-pingmesh-exporter
sources:
- https://github.com/kubeservice-stack/pingmesh-agent
type: application
version: 1.0.1
