apiVersion: v1
kind: Service
metadata:
  name: {{ template "gohttpserver.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
{{ include "gohttpserver.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "gohttpserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
